### ISSUE TITLE
[Issue]: HSA_STATUS_ERROR_INVALID_PACKET_FORMAT when running NUTS (while-loop) inside lax.scan on ROCm gfx1151

### ISSUE THREAD

**Issue by jcalifornia** [ROCm/rocm-jax#375]
### Problem Description

Error: "HSA_STATUS_ERROR_INVALID_PACKET_FORMAT: The AQL packet is malformed. " when running BlackJAX NUTS kernel inside of jax.lax.scan

### Operating System

24.04.4 LTS (Noble Numbat)

### CPU

 AMD Ryzen AI MAX+ 395

### GPU

gfx1151

### ROCm Version

7.2.0

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

```                                                                                                                
  import os                                                                                                      
  os.environ["JAX_ENABLE_X64"] = "1"                                                                             
                                                                  
  import jax
  import jax.numpy as jnp
  import blackjax

  def log_prob(x):                                                                                               
      return -0.5 * jnp.sum(x ** 2)
                                                                                                                 
  key = jax.random.PRNGKey(0)                                     
  inv_mass = jnp.ones(5)
  kernel = blackjax.nuts(log_prob, step_size=0.1, inverse_mass_matrix=inv_mass)                                  
  state = kernel.init(jnp.zeros(5))
                                                                                                                 
  # ✅ Single step works                                                                                         
  new_state, info = kernel.step(key, state)
  print(f"Single step: logp={float(new_state.logdensity):.2f}")                                                  
                                                                                                                 
  # ✅ HMC in scan works
  hmc_kernel = blackjax.hmc(                                                                                     
      log_prob, step_size=0.1,                                    
      inverse_mass_matrix=inv_mass,                                                                              
      num_integration_steps=10,
  )                                                                                                              
  hmc_state = hmc_kernel.init(jnp.zeros(5))                       
                                                                                                                 
  def hmc_step(carry, key):
      new_state, info = hmc_kernel.step(key, carry)                                                              
      return new_state, new_state.position                        

  keys = jax.random.split(key, 30)                                                                               
  final, positions = jax.lax.scan(hmc_step, hmc_state, keys)
  print(f"HMC scan: {positions.shape}")  # works                                                                 
                                                                                                                 
  # ❌ NUTS in scan crashes
  def nuts_step(carry, key):                                                                                     
      new_state, info = kernel.step(key, carry)                   
      return new_state, (new_state.logdensity, info.is_divergent)
                                                                                                                 
  keys = jax.random.split(key, 10)
  final, (logps, divs) = jax.lax.scan(nuts_step, state, keys)                                                    
  print(f"NUTS scan: {logps.shape}")  # may print, then crashes   
                                                                                                                 
  # Any subsequent JAX operation triggers the deferred crash:                                                    
  _ = jnp.ones(1) + 1                                                                                            
```

  Error output:
  rocdevice.cpp:3586: Callback: Queue 0x... aborting with error :
    HSA_STATUS_ERROR_INVALID_PACKET_FORMAT: The AQL packet is malformed. code: 0x1009

  *** Check failure stack trace: ***
    stream_executor::gpu::RocmContext::SetActive()
    stream_executor::gpu::RocmContext::GetDeviceMemoryUsage()
    xla::StreamExecutorGpuClient::CompileAndLoad()
    ...

**Comment by lucbruni-amd** [comment]
Hi @jcalifornia, thanks for reporting this issue.

Could you provide some additional information:

- `pip freeze | grep -iE '^jax|rocm|blackjax'` and JAX install method
- `uname -r` and `amd-smi` outputs

Thanks!

**Comment by lucbruni-amd** [comment]
@jcalifornia, are you still encountering the issue? If so, we can investigate starting with further information as I've requested above.

**Comment by jcalifornia** [comment]
Sorry I will post later today, have been busy with other things

**Comment by jcalifornia** [comment]
sorry for the delay,  I installed jax using pip directly from this repo `pip3 install --break-system-packages https://github.com/ROCm/jax/releases/download/rocm-jax-v0.7.1/jaxlib-0.7.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl`

I also tried a week or two ago on the newer release of rocm-jax and ran into a different error that I didn't record

```
→ pip freeze | grep -iE '^jax|rocm|blackjax'
amdsmi @ file:///opt/rocm-7.2.0/share/amd_smi
jax==0.7.1
jax-rocm7-pjrt==0.7.1
jax-rocm7-plugin==0.7.1
jaxlib==0.7.1

→ uname -r
6.17.0-1011-oem

→ amd-smi
+------------------------------------------------------------------------------+
| AMD-SMI 26.2.1+fc0010cf6a    amdgpu version: Linuxver ROCm version: 7.2.0    |
| VBIOS version: 023.011.000.039.000001                                        |
| Platform: Linux Baremetal                                                    |
|-------------------------------------+----------------------------------------|
| BDF                        GPU-Name | Mem-Uti   Temp   UEC       Power-Usage |
| GPU  HIP-ID  OAM-ID  Partition-Mode | GFX-Uti    Fan               Mem-Usage |
|=====================================+========================================|
| 0000:c6:00.0    AMD Radeon Graphics | N/A        N/A   0                 N/A |
|   0       0     N/A             N/A | N/A        N/A             914/1024 MB |
+-------------------------------------+----------------------------------------+
+------------------------------------------------------------------------------+
| Processes:                                                                   |
|  GPU        PID  Process Name          GTT_MEM  VRAM_MEM  MEM_USAGE     CU % |
|==============================================================================|
|  No running processes found                                                  |
+------------------------------------------------------------------------------+

```

**Comment by jcalifornia** [comment]
I updated to v0.9.1 and it looks like the error is gone, so something fixed it. I'm going to close this issue

**Comment by lucbruni-amd** [comment]
Thanks for the update and additional info. Glad to hear you were able to resolve it with 0.9.1. If you encounter any further bugs feel free to open more [Github issues](https://github.com/ROCm/rocm-jax/issues).
